# -*- coding: utf-8 -*-
"""neg,num,punc,comp,later,clini,unit,sen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGw_ygaHcCdUO0ga_Gj8dtjWmmu3cXlP
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import re


BASE_DIR = "/content/drive/MyDrive/dentist_project"
GT_DIR = os.path.join(BASE_DIR, "conversations")
TRANSCRIPT_DIR = os.path.join(BASE_DIR, "transcripts")

pairs = [
    ("Conversation1.txt", "transcript_conversation1.txt", "medasr_conversation1.txt"),
    ("Conversation2.txt", "transcript_conversation2.txt", "medasr_conversation2.txt"),
]

!pip install jiwer

"""**Clinical_coherence:**"""

from jiwer import wer

print("\nCLINICAL COHERENCE SCORE")

for gt_file, whisper_file, medasr_file in pairs:
    gt = open(os.path.join(GT_DIR, gt_file)).read().lower()
    whisper = open(os.path.join(TRANSCRIPT_DIR, whisper_file)).read().lower()
    medasr = open(os.path.join(TRANSCRIPT_DIR, medasr_file)).read().lower()

    whisper_score = 1 - wer(gt, whisper)
    medasr_score = 1 - wer(gt, medasr)

    print(f"\n{gt_file}")
    print("Whisper Coherence:", round(whisper_score, 3))
    print("MedASR  Coherence:", round(medasr_score, 3))

"""**Completeness_rate:**"""

print("\nCOMPLETENESS RATE")

def completeness(gt, pred):
    gt_words = set(gt.split())
    pred_words = set(pred.split())
    return len(gt_words & pred_words) / len(gt_words)

for gt_file, whisper_file, medasr_file in pairs:
    gt = open(os.path.join(GT_DIR, gt_file)).read().lower()
    whisper = open(os.path.join(TRANSCRIPT_DIR, whisper_file)).read().lower()
    medasr = open(os.path.join(TRANSCRIPT_DIR, medasr_file)).read().lower()

    print(f"\n{gt_file}")
    print("Whisper Completeness:", round(completeness(gt, whisper), 3))
    print("MedASR  Completeness:", round(completeness(gt, medasr), 3))

"""**Laterality accuracy:**"""

print("\nLATERALITY ACCURACY")

LATERAL_TERMS = ["left", "right", "upper left", "upper right", "lower left", "lower right"]

def laterality_accuracy(gt, pred):
    gt_terms = [t for t in LATERAL_TERMS if t in gt]
    pred_terms = [t for t in gt_terms if t in pred]
    return len(pred_terms) / len(gt_terms) if gt_terms else 1.0

for gt_file, whisper_file, medasr_file in pairs:
    gt = open(os.path.join(GT_DIR, gt_file)).read().lower()
    whisper = open(os.path.join(TRANSCRIPT_DIR, whisper_file)).read().lower()
    medasr = open(os.path.join(TRANSCRIPT_DIR, medasr_file)).read().lower()

    print(f"\n{gt_file}")
    print("Whisper Laterality:", laterality_accuracy(gt, whisper))
    print("MedASR  Laterality:", laterality_accuracy(gt, medasr))

"""**Negation accuracy:**"""

print("\nNEGATION ACCURACY")

NEGATIONS = ["no", "not", "without", "denies"]

def negation_accuracy(gt, pred):
    gt_neg = [n for n in NEGATIONS if n in gt]
    pred_neg = [n for n in gt_neg if n in pred]
    return len(pred_neg) / len(gt_neg) if gt_neg else 1.0

for gt_file, whisper_file, medasr_file in pairs:
    gt = open(os.path.join(GT_DIR, gt_file)).read().lower()
    whisper = open(os.path.join(TRANSCRIPT_DIR, whisper_file)).read().lower()
    medasr = open(os.path.join(TRANSCRIPT_DIR, medasr_file)).read().lower()

    print(f"\n{gt_file}")
    print("Whisper Negation:", negation_accuracy(gt, whisper))
    print("MedASR  Negation:", negation_accuracy(gt, medasr))

"""**Numeric accuracy:**"""

print("\nNUMERIC ACCURACY")

def extract_numbers(text):
    return re.findall(r"\d+\.?\d*", text)

def numeric_accuracy(gt, pred):
    gt_nums = extract_numbers(gt)
    pred_nums = extract_numbers(pred)
    return len(set(gt_nums) & set(pred_nums)) / len(gt_nums) if gt_nums else 1.0

for gt_file, whisper_file, medasr_file in pairs:
    gt = open(os.path.join(GT_DIR, gt_file)).read().lower()
    whisper = open(os.path.join(TRANSCRIPT_DIR, whisper_file)).read().lower()
    medasr = open(os.path.join(TRANSCRIPT_DIR, medasr_file)).read().lower()

    print(f"\n{gt_file}")
    print("Whisper Numeric:", numeric_accuracy(gt, whisper))
    print("MedASR  Numeric:", numeric_accuracy(gt, medasr))

"""**Punctuation accuracy:**"""

print("\nPUNCTUATION ACCURACY")

def punctuation_accuracy(gt, pred):
    gt_p = re.findall(r"[.,!?]", gt)
    pred_p = re.findall(r"[.,!?]", pred)
    return len(pred_p) / len(gt_p) if gt_p else 1.0

for gt_file, whisper_file, medasr_file in pairs:
    gt = open(os.path.join(GT_DIR, gt_file)).read()
    whisper = open(os.path.join(TRANSCRIPT_DIR, whisper_file)).read()
    medasr = open(os.path.join(TRANSCRIPT_DIR, medasr_file)).read()

    print(f"\n{gt_file}")
    print("Whisper Punctuation:", punctuation_accuracy(gt, whisper))
    print("MedASR  Punctuation:", punctuation_accuracy(gt, medasr))

"""**Section accuracy:**"""

SECTIONS = ["subjective", "objective", "assessment", "plan"]

def section_accuracy(gt, pred):
    gt_sections = [s for s in SECTIONS if s in gt]
    pred_sections = [s for s in gt_sections if s in pred]
    return len(pred_sections) / len(gt_sections) if gt_sections else 1.0


print("\nSECTION ACCURACY")

for gt_file, whisper_file, medasr_file in pairs:
    gt = open(os.path.join(GT_DIR, gt_file), encoding="utf-8").read().lower()

    whisper = open(
        os.path.join(TRANSCRIPT_DIR, whisper_file),
        encoding="utf-8"
    ).read().lower()

    medasr = open(
        os.path.join(TRANSCRIPT_DIR, medasr_file),
        encoding="utf-8"
    ).read().lower()

    print(f"\n{gt_file}")
    print("Whisper Section Accuracy :", round(section_accuracy(gt, whisper), 3))
    print("MedASR  Section Accuracy :", round(section_accuracy(gt, medasr), 3))

"""**sentence difference:**"""

print("\nSENTENCE DIFFERENCE")

def sentence_diff(gt, pred):
    return abs(len(gt.split(".")) - len(pred.split(".")))

for gt_file, whisper_file, medasr_file in pairs:
    gt = open(os.path.join(GT_DIR, gt_file)).read()
    whisper = open(os.path.join(TRANSCRIPT_DIR, whisper_file)).read()
    medasr = open(os.path.join(TRANSCRIPT_DIR, medasr_file)).read()

    print(f"\n{gt_file}")
    print("Whisper Sentence Diff:", sentence_diff(gt, whisper))
    print("MedASR  Sentence Diff:", sentence_diff(gt, medasr))

"""**unit accuracy:**"""

UNITS = ["mg", "ml", "mm", "cm", "units", "tablet", "capsule"]

def unit_accuracy(gt, pred):
    gt_units = re.findall(r"\b\d+\s?(mg|ml|mm|cm|units|tablet|capsule)\b", gt)
    pred_units = re.findall(r"\b\d+\s?(mg|ml|mm|cm|units|tablet|capsule)\b", pred)

    return len(set(gt_units) & set(pred_units)) / len(gt_units) if gt_units else 1.0


print("\nUNIT ACCURACY")

for gt_file, whisper_file, medasr_file in pairs:
    gt = open(os.path.join(GT_DIR, gt_file), encoding="utf-8").read().lower()
    whisper = open(os.path.join(TRANSCRIPT_DIR, whisper_file), encoding="utf-8").read().lower()
    medasr = open(os.path.join(TRANSCRIPT_DIR, medasr_file), encoding="utf-8").read().lower()

    print(f"\n{gt_file}")
    print("Whisper Unit Accuracy:", round(unit_accuracy(gt, whisper), 3))
    print("MedASR  Unit Accuracy:", round(unit_accuracy(gt, medasr), 3))

"""**Medication dosage accuracy:**"""

import re

MEDICATIONS = [
    "amoxicillin",
    "ibuprofen",
    "paracetamol",
    "lidocaine",
    "acetaminophen"
]

def extract_med_dosage(text):
    pattern = r"(amoxicillin|ibuprofen|paracetamol|lidocaine|acetaminophen)\s+\d+\s?(mg|ml)"
    return re.findall(pattern, text)

def medication_dosage_accuracy(gt, pred):
    gt_pairs = extract_med_dosage(gt)
    pred_pairs = extract_med_dosage(pred)

    return len(set(gt_pairs) & set(pred_pairs)) / len(gt_pairs) if gt_pairs else 1.0


print("\nMEDICATION DOSAGE ACCURACY")

for gt_file, whisper_file, medasr_file in pairs:
    gt = open(os.path.join(GT_DIR, gt_file), encoding="utf-8").read().lower()
    whisper = open(os.path.join(TRANSCRIPT_DIR, whisper_file), encoding="utf-8").read().lower()
    medasr = open(os.path.join(TRANSCRIPT_DIR, medasr_file), encoding="utf-8").read().lower()

    print(f"\n{gt_file}")
    print("Whisper Medication Dosage:", round(medication_dosage_accuracy(gt, whisper), 3))
    print("MedASR  Medication Dosage:", round(medication_dosage_accuracy(gt, medasr), 3))